import * as api from "./api/index.ts";
export { api };
import * as apiextensionsApiserver from "./apiextensions-apiserver/index.ts";
export { apiextensionsApiserver };
import * as apimachinery from "./apimachinery/index.ts";
export { apimachinery };
import * as kubeAggregator from "./kube-aggregator/index.ts";
export { kubeAggregator };
import * as admissionregistrationK8sIo from "./admissionregistration.k8s.io/index.ts";
export { admissionregistrationK8sIo };
import * as apps from "./apps/index.ts";
export { apps };
import * as auditregistrationK8sIo from "./auditregistration.k8s.io/index.ts";
export { auditregistrationK8sIo };
import * as authenticationK8sIo from "./authentication.k8s.io/index.ts";
export { authenticationK8sIo };
import * as authorizationK8sIo from "./authorization.k8s.io/index.ts";
export { authorizationK8sIo };
import * as autoscaling from "./autoscaling/index.ts";
export { autoscaling };
import * as batch from "./batch/index.ts";
export { batch };
import * as certificatesK8sIo from "./certificates.k8s.io/index.ts";
export { certificatesK8sIo };
import * as coordinationK8sIo from "./coordination.k8s.io/index.ts";
export { coordinationK8sIo };
import * as v1 from "./v1/index.ts";
export { v1 };
import * as discoveryK8sIo from "./discovery.k8s.io/index.ts";
export { discoveryK8sIo };
import * as eventsK8sIo from "./events.k8s.io/index.ts";
export { eventsK8sIo };
import * as extensions from "./extensions/index.ts";
export { extensions };
import * as flowcontrolApiserverK8sIo from "./flowcontrol.apiserver.k8s.io/index.ts";
export { flowcontrolApiserverK8sIo };
import * as networkingK8sIo from "./networking.k8s.io/index.ts";
export { networkingK8sIo };
import * as nodeK8sIo from "./node.k8s.io/index.ts";
export { nodeK8sIo };
import * as policy from "./policy/index.ts";
export { policy };
import * as rbacAuthorizationK8sIo from "./rbac.authorization.k8s.io/index.ts";
export { rbacAuthorizationK8sIo };
import * as schedulingK8sIo from "./scheduling.k8s.io/index.ts";
export { schedulingK8sIo };
import * as settingsK8sIo from "./settings.k8s.io/index.ts";
export { settingsK8sIo };
import * as storageK8sIo from "./storage.k8s.io/index.ts";
export { storageK8sIo };
import * as apiextensionsK8sIo from "./apiextensions.k8s.io/index.ts";
export { apiextensionsK8sIo };
import * as admissionK8sIo from "./admission.k8s.io/index.ts";
export { admissionK8sIo };
import * as apiregistrationK8sIo from "./apiregistration.k8s.io/index.ts";
export { apiregistrationK8sIo };
import * as imagepolicyK8sIo from "./imagepolicy.k8s.io/index.ts";
export { imagepolicyK8sIo };
