import * as admissionregistration from "./admissionregistration/index.ts";
export { admissionregistration };
import * as apps from "./apps/index.ts";
export { apps };
import * as auditregistration from "./auditregistration/index.ts";
export { auditregistration };
import * as authentication from "./authentication/index.ts";
export { authentication };
import * as authorization from "./authorization/index.ts";
export { authorization };
import * as autoscaling from "./autoscaling/index.ts";
export { autoscaling };
import * as batch from "./batch/index.ts";
export { batch };
import * as certificates from "./certificates/index.ts";
export { certificates };
import * as coordination from "./coordination/index.ts";
export { coordination };
import * as core from "./core/index.ts";
export { core };
import * as discovery from "./discovery/index.ts";
export { discovery };
import * as events from "./events/index.ts";
export { events };
import * as extensions from "./extensions/index.ts";
export { extensions };
import * as flowcontrol from "./flowcontrol/index.ts";
export { flowcontrol };
import * as networking from "./networking/index.ts";
export { networking };
import * as node from "./node/index.ts";
export { node };
import * as policy from "./policy/index.ts";
export { policy };
import * as rbac from "./rbac/index.ts";
export { rbac };
import * as scheduling from "./scheduling/index.ts";
export { scheduling };
import * as settings from "./settings/index.ts";
export { settings };
import * as storage from "./storage/index.ts";
export { storage };
